// Users
export const USERS_READ = 'USERS:READ'
export const USERS_WRITE = 'USERS:WRITE'

// Skills
export const SKILLS_READ = 'SKILLS:READ'
export const SKILLS_WRITE = 'SKILLS:WRITE'
export const SKILLS_DELETE = 'SKILLS:DELETE'

// Departments
export const DEPARTMENTS_READ = 'DEPARTMENTS:READ'
export const DEPARTMENTS_WRITE = 'DEPARTMENTS:WRITE'
export const DEPARTMENTS_DELETE = 'DEPARTMENTS:DELETE'

// Qualifications
export const QUALIFICATIONS_READ = 'QUALIFICATIONS:READ'
export const QUALIFICATIONS_WRITE = 'QUALIFICATIONS:WRITE'
export const QUALIFICATIONS_DELETE = 'QUALIFICATIONS:DELETE'

// Qualifications Types
export const QUALIFICATION_TYPES_READ = 'QUALIFICATION_TYPES:READ'
export const QUALIFICATION_TYPES_WRITE = 'QUALIFICATION_TYPES:WRITE'
export const QUALIFICATION_TYPES_DELETE = 'QUALIFICATION_TYPES:DELETE'

// REQUIREMENTS
export const REQUIREMENTS_READ = 'REQUIREMENTS:READ'
export const REQUIREMENTS_WRITE = 'REQUIREMENTS:WRITE'
export const REQUIREMENTS_DELETE = 'REQUIREMENTS:DELETE'

// MATERIALS
export const MATERIALS_READ = 'MATERIALS:READ'
export const MATERIALS_WRITE = 'MATERIALS:WRITE'
export const MATERIALS_DELETE = 'MATERIALS:DELETE'

// SUCCESS CRITERIAS
export const SKILL_SUCCESS_CRITERIAS_READ = 'SKILL_SUCCESS_CRITERIAS:READ'
export const SKILL_SUCCESS_CRITERIAS_WRITE = 'SKILL_SUCCESS_CRITERIAS:WRITE'
export const SKILL_SUCCESS_CRITERIAS_DELETE = 'SKILL_SUCCESS_CRITERIAS:DELETE'
