// IP
export const IP_ADD = 'IP_ADD'
export const IP_DELETE = 'IP_DELETE'
export const IP_LIST = 'IP_LIST'

// User
export const GET_USER_FETCHING = 'GET_USER_FETCHING'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

// Users

export const GET_USERS_FETCHING = 'GET_USERS_FETCHING'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const UPDATE_USER_BY_ID_FETCHING = 'UPDATE_USER_BY_ID_FETCHING'
export const UPDATE_USER_BY_ID_SUCCESS = 'UPDATE_USER_BY_ID_SUCCESS'

// Departments
export const GET_DEPARTMENTS_FETCHING = 'GET_DEPARTMENTS_FETCHING'
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS'
export const CREATE_DEPARTMENT_FETCHING = 'CREATE_DEPARTMENT_FETCHING'
export const CREATE_DEPARTMENT_SUCCESS = 'CREATE_DEPARTMENT_SUCCESS'
export const REMOVE_DEPARTMENT_BY_ID_FETCHING = 'REMOVE_DEPARTMENT_BY_ID_FETCHING'
export const REMOVE_DEPARTMENT_BY_ID_SUCCESS = 'REMOVE_DEPARTMENT_BY_ID_SUCCESS'
export const UPDATE_DEPARTMENT_BY_ID_FETCHING = 'UPDATE_DEPARTMENT_BY_ID_FETCHING'
export const UPDATE_DEPARTMENT_BY_ID_SUCCESS = 'UPDATE_DEPARTMENT_BY_ID_SUCCESS'

// Qualification Types
export const GET_QUALIFICATIONS_TYPE_FETCHING = 'GET_QUALIFICATIONS_TYPE_FETCHING'
export const GET_QUALIFICATIONS_TYPE_SUCCESS = 'GET_QUALIFICATIONS_TYPE_SUCCESS'
export const CREATE_QUALIFICATION_TYPE_FETCHING = 'CREATE_QUALIFICATION_TYPE_FETCHING'
export const CREATE_QUALIFICATION_TYPE_SUCCESS = 'CREATE_QUALIFICATION_TYPE_SUCCESS'
export const REMOVE_QUALIFICATION_TYPE_BY_ID_FETCHING = 'REMOVE_QUALIFICATION_TYPE_BY_ID_FETCHING'
export const REMOVE_QUALIFICATION_TYPE_BY_ID_SUCCESS = 'REMOVE_QUALIFICATION_TYPE_BY_ID_SUCCESS'
export const UPDATE_QUALIFICATION_TYPE_BY_ID_FETCHING = 'UPDATE_QUALIFICATION_TYPE_BY_ID_FETCHING'
export const UPDATE_QUALIFICATION_TYPE_BY_ID_SUCCESS = 'UPDATE_QUALIFICATION_TYPE_BY_ID_SUCCESS'

// Qualification
export const CREATE_QUALIFICATION_FETCHING = 'CREATE_QUALIFICATION_FETCHING'
export const CREATE_QUALIFICATION_SUCCESS = 'CREATE_QUALIFICATION_SUCCESS'
export const UPDATE_QUALIFICATION_FETCHING = 'UPDATE_QUALIFICATION_FETCHING'
export const UPDATE_QUALIFICATION_SUCCESS = 'UPDATE_QUALIFICATION_SUCCESS'
export const REMOVE_QUALIFICATION_FETCHING = 'REMOVE_QUALIFICATION_FETCHING'
export const REMOVE_QUALIFICATION_SUCCESS = 'REMOVE_QUALIFICATION_SUCCESS'

// Categories
export const GET_CATEGORIES_FETCHING = 'GET_CATEGORIES_FETCHING'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const CREATE_CATEGORY_FETCHING = 'CREATE_CATEGORY_FETCHING'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const REMOVE_CATEGORY_BY_ID_FETCHING = 'REMOVE_CATEGORY_BY_ID_FETCHING'
export const REMOVE_CATEGORY_BY_ID_SUCCESS = 'REMOVE_CATEGORY_BY_ID_SUCCESS'
export const UPDATE_CATEGORY_BY_ID_FETCHING = 'UPDATE_CATEGORY_BY_ID_FETCHING'
export const UPDATE_CATEGORY_BY_ID_SUCCESS = 'UPDATE_CATEGORY_BY_ID_SUCCESS'

// Skills
export const GET_SKILL_BY_ID_FETCHING = 'GET_SKILL_BY_ID_FETCHING'
export const GET_SKILL_BY_ID_SUCCESS = 'GET_SKILL_BY_ID_SUCCESS'

// Requirements
export const GET_REQUIREMENT_FETCHING = 'GET_REQUIREMENT_FETCHING'
export const GET_REQUIREMENT_SUCCESS = 'GET_REQUIREMENT_SUCCESS'
export const CREATE_REQUIREMENT_FETCHING = 'CREATE_REQUIREMENT_FETCHING'
export const CREATE_REQUIREMENT_SUCCESS = 'CREATE_REQUIREMENT_SUCCESS'
export const UPDATE_REQUIREMENT_FETCHING = 'UPDATE_REQUIREMENT_FETCHING'
export const UPDATE_REQUIREMENT_SUCCESS = 'UPDATE_REQUIREMENT_SUCCESS'
export const REMOVE_REQUIREMENT_FETCHING = 'REMOVE_REQUIREMENT_FETCHING'
export const REMOVE_REQUIREMENT_SUCCESS = 'REMOVE_REQUIREMENT_SUCCESS'

// Requirements Types
export const GET_REQUIREMENTS_TYPES_FETCHING = 'GET_REQUIREMENTS_TYPES_FETCHING'
export const GET_REQUIREMENTS_TYPES_SUCCESS = 'GET_REQUIREMENTS_TYPES_SUCCESS'

// Materials
export const CREATE_MATERIAL_FETCHING = 'CREATE_MATERIAL_FETCHING'
export const CREATE_MATERIAL_SUCCESS = 'CREATE_MATERIAL_SUCCESS'
export const REMOVE_MATERIAL_FETCHING = 'REMOVE_MATERIAL_FETCHING'
export const REMOVE_MATERIAL_SUCCESS = 'REMOVE_MATERIAL_SUCCESS'
export const UPDATE_MATERIAL_FETCHING = 'UPDATE_MATERIAL_FETCHING'
export const UPDATE_MATERIAL_SUCCESS = 'UPDATE_MATERIAL_SUCCESS'

// Criteria
export const CREATE_CRITERIA_FETCHING = 'CREATE_CRITERIA_FETCHING'
export const CREATE_CRITERIA_SUCCESS = 'CREATE_CRITERIA_SUCCESS'
export const REMOVE_CRITERIA_FETCHING = 'REMOVE_CRITERIA_FETCHING'
export const REMOVE_CRITERIA_SUCCESS = 'REMOVE_CRITERIA_SUCCESS'
export const UPDATE_CRITERIA_FETCHING = 'UPDATE_CRITERIA_FETCHING'
export const UPDATE_CRITERIA_SUCCESS = 'UPDATE_CRITERIA_SUCCESS'

// Roles

export const GET_ROLES_FETCHING = 'GET_ROLES_FETCHING'
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS'
